### ISSUE TITLE
Работа вентиляторов 12000 RPM

### ISSUE THREAD

**Issue by Var1ant13** [FB-G6/Marlin#10]
В прошивке v2.1.2.8rc3 вентиляторы обдува GDSTime 4010 на 12000 оборотов работают только в режиме 100%. На предыдущей прошивке (v2.1.2.7) они без проблем запускаются начиная с уровня 7%.

**Comment by tarwirdur** [comment]
Это исправлено в последней выложенной сборке ( https://github.com/FB-G6/Marlin/releases/tag/dev-20230709 )

Исправление: https://github.com/FB-G6/Marlin/commit/c3b2c578dc8518a0c81d8dbf7c39bacf4d53c5a4

Issue закрываю, если вдруг проблема на последней сборке всё равно воспроизводится - переоткройте .
