### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by MacOS14** [FB-G6/Marlin#8]
Good evening
You can add the ability to delete files from the CD card.
After calibration, BLTouch stopped at the 9 mark, I press the seal and the orientation of the head with Hom
Home for the Head was counted as the 9th mark of Calibration
And is it possible to add WIfi from the marlin menu
thank you

**Comment by tarwirdur** [comment]
> After calibration, BLTouch stopped at the 9 mark, I press the seal and the orientation of the head with Hom
> Home for the Head was counted as the 9th mark of Calibration

I'm not sure I understood you. Can you describe in more detail? Could you show your starting gcode?

> And is it possible to add WIfi from the marlin menu

There is a button to read wifi parameters from SD from `wifi.txt` file. Doesn't this solve the problem?

The functionality of choosing a network and entering a password using the on-screen keyboard is not very easy to do.
