### ISSUE TITLE
Ошибка печати 

### ISSUE THREAD

**Issue by Kulikkk** [FB-G6/Marlin#9]
Translate my text to english thx 
В кратце проблема при печати больших моделей просто при окончание первые 1-3 слоев пищит перезагружается и не возможно продолжить печать проблема не в gcode так как на другом принтере FB Reborn 2 с фул мои кастомной прошивкой работает и печатает ту же самую модель с тем же gcode хорошо

**Comment by tarwirdur** [comment]
Пишет ли что-то на экране во время писка? Писк длинный или это обычный писк при включении?

Достигается ли заданная температура? Похожее поведение может возникнуть если неправильно заменить горло на биметаллическое. [Узкая часть горла должна быть целиком над кубиком](https://github.com/Tombraider2006/klipperFB6/raw/main/what_2_buy/soplo2.jpg).

**Comment by Kulikkk** [comment]
Нет просто длинный писк и перезагружается , дальше печать продолжить не возможно 
Горло не трогалось пока что нету нужды в этом ошибка не может быть иза механики все идеально настроено,натянуто,вкручено 
У меня до этого не было таких проблем думаю может откатиться до 2.1.2.6 может поможет  
Я подумал изначально проблема в gcode 3d модели но на реборне 2 всё напечаталось отлично 
Если не затруднит я бы хотел пообщаться с тобой в телег об этом . @dm_itry_kulikov
